version: '3.2'
services:
  consumer-microservice:
    image: consumer-microservice
    build: .
    ports:
      - "8090:8090"
    container_name: consumer-microservice
    depends_on:
      - postgres
  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=consumer

